"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { Html5Qrcode } from "html5-qrcode";
import styles from "./scanner.module.css";
type Result = { status: "VALID" | "ALREADY_USED" | "INVALID_TICKET"; entryAllowed: boolean; message: string; reason?: string; ticketReference?: string; eventDay?: string | null; ticketType?: string | null };
export function ScannerClient() {
  const scanner = useRef<Html5Qrcode | null>(null); const locked = useRef(false); const [camera, setCamera] = useState<"idle" | "starting" | "active" | "error">("idle"); const [cameraError, setCameraError] = useState(""); const [result, setResult] = useState<Result | null>(null); const [manual, setManual] = useState("");
  const stop = useCallback(async () => { const current = scanner.current; scanner.current = null; if (!current) return; try { await current.stop(); } catch {} try { await current.clear(); } catch {} }, []);
  const submit = useCallback(async (value: string) => { if (locked.current) return; locked.current = true; try { const response = await fetch("/api/scanner/scan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticketReference: value.trim().toUpperCase() }) }); const data = await response.json().catch(() => null); setResult(response.ok && data ? data : { status: "INVALID_TICKET", entryAllowed: false, message: "ENTRY DENIED", reason: "SCAN COULD NOT BE VERIFIED" }); } catch { setResult({ status: "INVALID_TICKET", entryAllowed: false, message: "ENTRY DENIED", reason: "NETWORK ERROR" }); } }, []);
  const start = useCallback(async () => { setCamera("starting"); setCameraError(""); try { const { Html5Qrcode } = await import("html5-qrcode"); const instance = new Html5Qrcode("navrang-qr-reader"); scanner.current = instance; await instance.start({ facingMode: "environment" }, { fps: 10, qrbox: { width: 230, height: 230 } }, (text) => void submit(text), () => undefined); setCamera("active"); } catch { await stop(); setCamera("error"); setCameraError("Camera access is unavailable. Check permission, HTTPS, and your device camera."); } }, [stop, submit]);
  const next = () => { locked.current = false; setResult(null); setManual(""); }; useEffect(() => () => { void stop(); }, [stop]);
  return <section className={styles.panel} aria-live="polite"><div className={styles.frame}><div id="navrang-qr-reader" /></div>{camera === "idle" || camera === "error" ? <button className="button" onClick={() => void start()} type="button">{camera === "error" ? "Try camera again" : "Open camera scanner"}</button> : null}{camera === "starting" ? <p className="muted">Opening camera…</p> : null}{camera === "active" && !result ? <p className={styles.status}>Point the camera at a Navrang ticket QR code.</p> : null}{cameraError ? <p className="form-error">{cameraError}</p> : null}{result ? <div className={`${styles.result} ${result.entryAllowed ? styles.valid : styles.denied}`}><p>{result.message}</p><h2>{result.entryAllowed ? "ENTRY ALLOWED" : "ENTRY DENIED"}</h2><strong>{result.reason}</strong>{result.ticketReference ? <span>{result.ticketReference}{result.eventDay ? ` · ${result.eventDay}` : ""}{result.ticketType ? ` · ${result.ticketType}` : ""}</span> : null}<button className="button" onClick={next} type="button">Scan next</button></div> : null}{process.env.NODE_ENV === "development" ? <form className={styles.manual} onSubmit={(event) => { event.preventDefault(); void submit(manual); }}><label>Development test reference<input value={manual} onChange={(event) => setManual(event.target.value)} placeholder="TKT-XXXXXXXX" pattern="TKT-[A-Z0-9]{8,32}" /></label><button className="button secondary-button" type="submit">Test reference</button></form> : null}</section>;
}
