"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { eventConfig, type TicketType } from "@/lib/event-config";
import { formatEventDate, formatPrice } from "@/lib/format";

type Step = "day" | "ticket" | "details" | "summary";
type Details = { name: string; mobile: string; email: string };
type DateSpecificPrice = { dayNumber: number; ticketTypeCode: Exclude<TicketType["code"], "EARLY_BIRD_9_DAY">; price: number };
const storageKey = "navrang-booking-draft";
const earlyBirdCode = "EARLY_BIRD_9_DAY" as const;
const indianMobile = /^(?:\+91)?[6-9]\d{9}$/;
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export function BookingFlow({ ticketTypes = eventConfig.ticketTypes, earlyBird, dateSpecificPrices = [] }: { ticketTypes?: readonly TicketType[]; earlyBird: TicketType | null; dateSpecificPrices?: ReadonlyArray<DateSpecificPrice> }) {
  const router = useRouter(); const [step, setStep] = useState<Step>("day"); const [dayNumber, setDayNumber] = useState<number | null>(null); const [ticketCode, setTicketCode] = useState<TicketType["code"] | null>(null); const [quantity, setQuantity] = useState(1); const [details, setDetails] = useState<Details>({ name: "", mobile: "", email: "" }); const [idempotencyKey, setIdempotencyKey] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const isEarlyBird = ticketCode === earlyBirdCode;
  useEffect(() => { const restoreDraft = window.setTimeout(() => { const saved = window.sessionStorage.getItem(storageKey); if (!saved) { setIdempotencyKey(crypto.randomUUID()); return; } try { const draft = JSON.parse(saved) as { step?: Step; dayNumber?: number; ticketCode?: TicketType["code"]; quantity?: number; details?: Details; idempotencyKey?: string }; setStep(draft.step ?? "day"); setDayNumber(draft.dayNumber ?? null); setTicketCode(draft.ticketCode ?? null); setQuantity(draft.ticketCode === earlyBirdCode ? 1 : draft.quantity ?? 1); setDetails(draft.details ?? { name: "", mobile: "", email: "" }); setIdempotencyKey(draft.idempotencyKey ?? crypto.randomUUID()); } catch { setIdempotencyKey(crypto.randomUUID()); } }, 0); return () => window.clearTimeout(restoreDraft); }, []);
  useEffect(() => { if (idempotencyKey) window.sessionStorage.setItem(storageKey, JSON.stringify({ step, dayNumber, ticketCode, quantity, details, idempotencyKey })); }, [step, dayNumber, ticketCode, quantity, details, idempotencyKey]);
  const selectedDay = useMemo(() => eventConfig.days.find((day) => day.number === dayNumber), [dayNumber]);
  const selectedTicket = useMemo(() => { if (ticketCode === earlyBirdCode) return earlyBird; const ticket = ticketTypes.find((item) => item.code === ticketCode); const override = dateSpecificPrices.find((item) => item.dayNumber === dayNumber && item.ticketTypeCode === ticketCode); return ticket && override ? { ...ticket, price: override.price } : ticket; }, [dayNumber, dateSpecificPrices, earlyBird, ticketCode, ticketTypes]);
  const canContinueTicket = Boolean(selectedTicket?.active && selectedTicket.price && selectedTicket.price > 0); const total = selectedTicket?.price ? selectedTicket.price * quantity : null;
  function chooseDay(number: number, active: boolean) { if (active) { setDayNumber(number); setTicketCode(null); setQuantity(1); setError(""); setStep("ticket"); } }
  function chooseEarlyBird() { if (earlyBird?.active) { setDayNumber(1); setTicketCode(earlyBirdCode); setQuantity(1); setError(""); setStep("details"); } }
  function validateDetails() { if (details.name.trim().length < 2) return "Enter your full name."; if (!indianMobile.test(details.mobile.replace(/[ -]/g, ""))) return "Enter a valid 10-digit Indian mobile number."; if (!emailPattern.test(details.email)) return "Enter a valid email address."; return ""; }
  async function createBooking() { const validationError = validateDetails(); if (validationError || !selectedDay || !selectedTicket || !canContinueTicket || (isEarlyBird && quantity !== 1)) { setError(validationError || "Ticket pricing is not configured yet."); return; } setSubmitting(true); setError(""); try { const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventDayNumber: selectedDay.number, ticketTypeCode: selectedTicket.code, quantity, ...details, idempotencyKey }) }); const result = await response.json() as { bookingReference?: string; error?: string }; if (!response.ok || !result.bookingReference) { setError(result.error ?? "We could not create your booking. Please try again."); return; } window.sessionStorage.removeItem(storageKey); router.push(`/booking/success?reference=${encodeURIComponent(result.bookingReference)}`); } catch { setError("Booking service is temporarily unavailable. Please try again later."); } finally { setSubmitting(false); } }
  const backToChoice = () => setStep(isEarlyBird ? "day" : "ticket");
  return <main className="container booking-page"><div className="booking-heading"><p className="eyebrow">Navrang Garba 2026</p><h1>Reserve your celebration.</h1><p className="page-intro">Choose an event night, or reserve the Early Bird 9-Day Pass.</p></div><ol className="progress" aria-label="Booking progress"><li className={step === "day" ? "current" : "complete"}>1. Day or Pass</li><li className={step === "ticket" ? "current" : (step === "details" || step === "summary" ? "complete" : "")}>2. Pass</li><li className={step === "details" ? "current" : step === "summary" ? "complete" : ""}>3. Details</li><li className={step === "summary" ? "current" : ""}>4. Review</li></ol>{error && <p className="form-error" role="alert">{error}</p>}
    {step === "day" && <section><h2>Choose your celebration</h2>{earlyBird?.active ? <article className="choice-card early-bird-card"><p className="eyebrow">EARLY BIRD</p><h3>9-Day Pass</h3><p>11–19 October 2026</p><strong>{formatPrice(earlyBird.price)}</strong><p>ONE QR • ALL 9 DAYS<br />ONE ENTRY PER DAY</p><button className="button" type="button" onClick={chooseEarlyBird}>Book 9-Day Pass</button></article> : null}<h3 className="normal-ticket-heading">Or choose an individual event day</h3><div className="day-grid booking-grid">{eventConfig.days.map((day) => <button type="button" key={day.number} className={`choice-card ${dayNumber === day.number ? "selected" : ""}`} disabled={!day.active} onClick={() => chooseDay(day.number, day.active)}><strong>{day.name}</strong><span>{formatEventDate(day.date)}</span>{!day.active && <small>Unavailable</small>}</button>)}</div></section>}
    {step === "ticket" && <section><button className="back-link" type="button" onClick={() => setStep("day")}>← Change day</button><h2>Choose your pass</h2><p className="selection-note">{selectedDay?.name} · {selectedDay && formatEventDate(selectedDay.date)}</p><div className="feature-grid">{ticketTypes.map((ticket) => { const override = dateSpecificPrices.find((item) => item.dayNumber === dayNumber && item.ticketTypeCode === ticket.code); const effectivePrice = override?.price ?? ticket.price; return <button type="button" key={ticket.code} className={`choice-card ticket-choice ${ticketCode === ticket.code ? "selected" : ""}`} disabled={!ticket.active} onClick={() => { if (ticket.active) { setTicketCode(ticket.code); setQuantity(1); setError(""); } }}><strong>{ticket.name}</strong><span>{ticket.description}</span><span>{ticket.capacity} {ticket.capacity === 1 ? "person" : "people"}</span><b>{formatPrice(effectivePrice)}</b>{!ticket.active && <small>Not available until pricing is confirmed</small>}</button>; })}</div>{selectedTicket && <div className="quantity-row"><label htmlFor="quantity">Number of {selectedTicket.name} passes</label><select id="quantity" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))}>{Array.from({ length: 10 }, (_, index) => <option key={index + 1} value={index + 1}>{index + 1}</option>)}</select></div>}<div className="flow-actions"><button className="button secondary-button" type="button" onClick={() => setStep("day")}>Back</button><button className="button" type="button" disabled={!canContinueTicket} onClick={() => { if (canContinueTicket) setStep("details"); }}>Continue</button></div></section>}
    {step === "details" && <section className="form-panel"><button className="back-link" type="button" onClick={backToChoice}>← Change pass</button><h2>Your details</h2>{isEarlyBird ? <p className="selection-note">Early Bird 9-Day Pass · Valid 11–19 October 2026 · One entry per event day.</p> : null}<div className="form-grid"><label>Full name<input value={details.name} maxLength={120} onChange={(event) => setDetails({ ...details, name: event.target.value })} autoComplete="name" /></label><label>Mobile number<input value={details.mobile} maxLength={20} onChange={(event) => setDetails({ ...details, mobile: event.target.value })} inputMode="tel" autoComplete="tel" placeholder="9876543210" /></label><label>Email *<input type="email" value={details.email} maxLength={254} onChange={(event) => setDetails({ ...details, email: event.target.value })} inputMode="email" autoComplete="email" required /></label></div><div className="flow-actions"><button className="button secondary-button" type="button" onClick={backToChoice}>Back</button><button className="button" type="button" onClick={() => { const message = validateDetails(); if (message) setError(message); else { setError(""); setStep("summary"); } }}>Review booking</button></div></section>}
    {step === "summary" && selectedDay && selectedTicket && <section className="summary-panel"><button className="back-link" type="button" onClick={() => setStep("details")}>← Edit details</button><h2>Review your booking</h2><dl className="summary-list"><div><dt>Event</dt><dd>Navrang Garba</dd></div><div><dt>{isEarlyBird ? "Validity" : "Day"}</dt><dd>{isEarlyBird ? "11–19 October 2026 · One entry per event day" : `${selectedDay.name} · ${formatEventDate(selectedDay.date)}`}</dd></div><div><dt>Pass</dt><dd>{isEarlyBird ? "Early Bird 9-Day Pass × 1" : `${selectedTicket.name} × ${quantity}`}</dd></div><div><dt>Price</dt><dd>{formatPrice(selectedTicket.price)} each</dd></div><div className="summary-total"><dt>Total</dt><dd>{formatPrice(total)}</dd></div><div><dt>Customer</dt><dd>{details.name}<br />{details.mobile}<br />{details.email}</dd></div></dl><p className="pending-note">This creates a payment-pending booking only. No ticket or QR code is issued until payment is verified.</p><div className="flow-actions"><button className="button secondary-button" type="button" onClick={() => setStep("details")}>Back</button><button className="button" type="button" disabled={submitting} onClick={createBooking}>{submitting ? "Creating booking…" : "Continue"}</button></div></section>}</main>;
}
